id = "paperclip01"

bind = "0.0.0.0:8443"
grpc_bind = "0.0.0.0:7443"
domain = "usercontent.solsynth.dev"

accepts_usage = [
    "p.avatar",
    "p.banner",
    "i.attachment",
    "m.attachment",
    "sticker",
]

[workers]
files_deletion = 4
files_analyze = 4

[debug]
database = true
print_routes = false

[dealer]
addr = "127.0.0.1:7442"

[security]
cookie_domain = "localhost"
cookie_samesite = "Lax"
access_token_duration = 300
refresh_token_duration = 2592000

[database]
dsn = "host=localhost user=postgres password=password dbname=hy_paperclip port=5432 sslmode=disable"
prefix = "paperclip_"

[pools.aliases]
"p.avatar" = "avatar"
"p.banner" = "avatar"
"i.attachment" = "interactive"
"m.attachment" = "messaging"
"sticker" = "sticker"

[destinations.temporary]
type = "local"
path = "uploads"

[destinations.permanent]
type = "local"
path = "uploads/permanent"
